const {
  parseChecklistText,
  normalizeIdentityName,
  namesMatch,
} = require('../utils/pdfChecklistParser');

const sampleChecklistText = `
2023 CURRICULUM FOR BACHELOR OF SCIENCE IN COMPUTER ENGINEERING (BSCPE)
IMPORTANT: Registration in any course/s without all the pre-requisite/s shall not be given any credit
SORIANO, DEXTER AIC MENDOZA2310675
 NAME:STUDENT NO:
COURSE CODE
COURSE TITLE
Credit
Units
FIRST YEAR, FIRST SEMESTER (20)
1.75CHM 001Chemistry for Engineers4
2.75MATH 141Calculus 14
1.75MATH 022BLinear Algebra with MATLAB3
CPEE 002
Cognate/Elective Course 2
3
Generated by: mdasoriano01@tip.edu.ph
on 05/03/2026 09:18 PM
Page 1 of 2
LEGEND
P = Pre-requisite
`;

describe('pdfChecklistParser', () => {
  test('extracts official checklist identity, curriculum title, and graded course rows', () => {
    const parsed = parseChecklistText(sampleChecklistText);

    expect(parsed.identity).toEqual({
      studentName: 'SORIANO, DEXTER AIC MENDOZA',
      studentNumber: '2310675',
    });
    expect(parsed.curriculumTitle).toContain('BACHELOR OF SCIENCE IN COMPUTER ENGINEERING');
    expect(parsed.rows).toEqual([
      { courseCode: 'CHM 001', grade: '1.75' },
      { courseCode: 'MATH 141', grade: '2.75' },
      { courseCode: 'MATH 022B', grade: '1.75' },
    ]);
  });

  test('matches comma-form official names against profile names with the same tokens', () => {
    expect(namesMatch('SORIANO, DEXTER AIC MENDOZA', 'Dexter Aic Mendoza Soriano')).toBe(true);
    expect(normalizeIdentityName('Soriano, Dexter  Aic Mendoza')).toBe(
      'SORIANO DEXTER AIC MENDOZA',
    );
    expect(namesMatch('SORIANO, DEXTER AIC MENDOZA', 'Ada Student')).toBe(false);
  });

  test('rejects PDFs without readable checklist text', () => {
    expect(() => parseChecklistText('')).toThrow(/Unable to read text from PDF/i);
  });
});
