import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import LogoutConfirmModal from "../components/LogoutConfirmModal";
import AdminLayout from "../components/admin/AdminLayout";
import AdviserLayout from "../components/adviser/AdviserLayout";
import StudentLayout from "../components/student/StudentLayout";

const YELLOW = "#FFC107";


const FAQ_ITEMS = [
  {
    question: "How do I view my academic record?",
    answer: 'Go to Dashboard → click “My Academic Record” from the quick links or navigate to My Record from the Home menu.',
  },
  {
    question: "How do I change my curriculum?",
    answer: "Curriculum changes must be requested through your academic adviser. Contact your assigned adviser via the advising portal or in person.",
  },
  {
    question: "Why can't I see my study plan?",
    answer: "Your study plan is generated by your adviser after your first advising session. If you have completed onboarding but still don't see a plan, contact your adviser.",
  },
  {
    question: "How do I update my profile information?",
    answer: "Go to Settings → Account → Edit Profile, or navigate directly to the Profile page from the sidebar.",
  },
  {
    question: "What does 'Needs Revalidation' mean on my study plan?",
    answer: "Your study plan is marked for revalidation when a new academic term begins or when your grades are updated. Your adviser will review and revalidate the plan.",
  },
  {
    question: "How are elective tracks assigned?",
    answer: "Elective tracks are selected during the advising process in Year 2, 2nd semester. Your adviser will help you choose a track that aligns with your interest.",
  },
  {
    question: "I forgot my password. What should I do?",
    answer: 'Click “Forgot your password?” on the login page. Enter your registered email and follow the reset link sent to your inbox.',
  },
];

const FaqItem = ({ question, answer }) => {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ borderBottom: "1px solid #f0f0f0" }}>
      <button
        onClick={() => setOpen((o) => !o)}
        style={{
          width: "100%",
          textAlign: "left",
          padding: "15px 0",
          background: "none",
          border: "none",
          cursor: "pointer",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          gap: 12,
        }}
      >
        <span style={{ fontWeight: 700, color: "#111", fontSize: "0.95rem" }}>{question}</span>
        <span style={{ fontSize: "1.1rem", color: YELLOW, fontWeight: 800, flexShrink: 0, transition: "transform 0.2s", transform: open ? "rotate(180deg)" : "none" }}>▾</span>
      </button>
      {open && (
        <p style={{ margin: "0 0 14px", fontSize: "0.88rem", color: "#555", lineHeight: 1.65 }}>{answer}</p>
      )}
    </div>
  );
};

const Help = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const [showLogoutConfirm, setShowLogoutConfirm] = useState(false);

  const handleLogout = async () => {
    await logout();
    navigate("/login");
  };

  // ── Admin / Adviser: render inside their own sidebar layout ──
  if (user?.role === 'admin' || user?.role === 'adviser') {
    const Layout = user.role === 'admin' ? AdminLayout : AdviserLayout;
    return (
      <Layout activePage="" pageTitle="Help & Support">
        <section style={{ background: "#fff", borderRadius: 16, padding: "24px 28px", marginBottom: 24, boxShadow: "0 2px 12px rgba(0,0,0,0.05)" }}>
          <h2 style={{ fontSize: "1.1rem", fontWeight: 800, color: "#111", marginBottom: 4 }}>Frequently Asked Questions</h2>
          <p style={{ fontSize: "0.83rem", color: "#888", marginBottom: 20, marginTop: 0 }}>Answers to common questions.</p>
          <div>
            {FAQ_ITEMS.map((item) => (
              <FaqItem key={item.question} question={item.question} answer={item.answer} />
            ))}
          </div>
        </section>
        <section style={{ background: "#fff", borderRadius: 16, padding: "24px 28px", boxShadow: "0 2px 12px rgba(0,0,0,0.05)" }}>
          <h2 style={{ fontSize: "1.1rem", fontWeight: 800, color: "#111", marginBottom: 4 }}>Contact Support</h2>
          <p style={{ fontSize: "0.83rem", color: "#888", marginBottom: 20, marginTop: 0 }}>Can't find what you're looking for? Reach out directly.</p>
          <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
            <div style={{ flex: "1 1 220px", padding: "18px 20px", borderRadius: 12, border: "1.5px solid #f0f0f0" }}>
              <div style={{ fontSize: "1.4rem", marginBottom: 8 }}>📧</div>
              <div style={{ fontWeight: 700, color: "#111", marginBottom: 4 }}>Email</div>
              <div style={{ fontSize: "0.85rem", color: "#888" }}>advising@tip.edu.ph</div>
            </div>
            <div style={{ flex: "1 1 220px", padding: "18px 20px", borderRadius: 12, border: "1.5px solid #f0f0f0" }}>
              <div style={{ fontSize: "1.4rem", marginBottom: 8 }}>🏫</div>
              <div style={{ fontWeight: 700, color: "#111", marginBottom: 4 }}>Office</div>
              <div style={{ fontSize: "0.85rem", color: "#888" }}>CPE Department, Room 317<br />Mon – Fri, 8AM – 5PM</div>
            </div>
            <div style={{ flex: "1 1 220px", padding: "18px 20px", borderRadius: 12, border: "1.5px solid #f0f0f0" }}>
              <div style={{ fontSize: "1.4rem", marginBottom: 8 }}>💬</div>
              <div style={{ fontWeight: 700, color: "#111", marginBottom: 4 }}>Talk to your Adviser</div>
              <div style={{ fontSize: "0.85rem", color: "#888" }}>Your academic adviser is your first point of contact for advising-related questions.</div>
            </div>
          </div>
        </section>
        <LogoutConfirmModal show={showLogoutConfirm} onCancel={() => setShowLogoutConfirm(false)} onConfirm={handleLogout} />
      </Layout>
    );
  }

  // ── Student: render inside shared student layout ──
  return (
    <StudentLayout activePage="help" pageTitle="Help & Support">
      {/* Quick links */}
          <section style={{ background: "#fff", borderRadius: 16, padding: "24px 28px", marginBottom: 24, boxShadow: "0 2px 12px rgba(0,0,0,0.05)" }}>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 800, color: "#111", marginBottom: 4 }}>Quick Help</h2>
            <p style={{ fontSize: "0.83rem", color: "#888", marginBottom: 20, marginTop: 0 }}>Jump to what you need.</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))", gap: 14 }}>
              {[
                { label: "My Academic Record", to: "/my-record", emoji: "📋" },
                { label: "View Grades", to: "/grades", emoji: "📊" },
                { label: "Study Plan", to: "/plan-of-study", emoji: "🗓️" },
                { label: "Checklist", to: "/checklist", emoji: "✅" },
                { label: "Available Subjects", to: "/subjects", emoji: "📚" },
                { label: "Edit Profile", to: "/profile", emoji: "👤" },
              ].map((item) => (
                <Link
                  key={item.to}
                  to={item.to}
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: 8,
                    padding: "18px 12px",
                    borderRadius: 12,
                    border: "1.5px solid #f0f0f0",
                    textDecoration: "none",
                    color: "#333",
                    fontWeight: 700,
                    fontSize: "0.85rem",
                    textAlign: "center",
                    transition: "border-color 0.15s, background 0.15s",
                  }}
                  onMouseEnter={(e) => { e.currentTarget.style.borderColor = YELLOW; e.currentTarget.style.background = "#fffbea"; }}
                  onMouseLeave={(e) => { e.currentTarget.style.borderColor = "#f0f0f0"; e.currentTarget.style.background = "#fff"; }}
                >
                  <span style={{ fontSize: "1.6rem" }}>{item.emoji}</span>
                  {item.label}
                </Link>
              ))}
            </div>
          </section>

          {/* FAQ */}
          <section style={{ background: "#fff", borderRadius: 16, padding: "24px 28px", marginBottom: 24, boxShadow: "0 2px 12px rgba(0,0,0,0.05)" }}>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 800, color: "#111", marginBottom: 4 }}>Frequently Asked Questions</h2>
            <p style={{ fontSize: "0.83rem", color: "#888", marginBottom: 20, marginTop: 0 }}>Answers to common questions from students.</p>
            <div>
              {FAQ_ITEMS.map((item) => (
                <FaqItem key={item.question} question={item.question} answer={item.answer} />
              ))}
            </div>
          </section>

          {/* Contact */}
          <section style={{ background: "#fff", borderRadius: 16, padding: "24px 28px", boxShadow: "0 2px 12px rgba(0,0,0,0.05)" }}>
            <h2 style={{ fontSize: "1.1rem", fontWeight: 800, color: "#111", marginBottom: 4 }}>Contact Support</h2>
            <p style={{ fontSize: "0.83rem", color: "#888", marginBottom: 20, marginTop: 0 }}>Can't find what you're looking for? Reach out directly.</p>
            <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
              <div style={{ flex: "1 1 220px", padding: "18px 20px", borderRadius: 12, border: "1.5px solid #f0f0f0" }}>
                <div style={{ fontSize: "1.4rem", marginBottom: 8 }}>📧</div>
                <div style={{ fontWeight: 700, color: "#111", marginBottom: 4 }}>Email</div>
                <div style={{ fontSize: "0.85rem", color: "#888" }}>advising@tip.edu.ph</div>
              </div>
              <div style={{ flex: "1 1 220px", padding: "18px 20px", borderRadius: 12, border: "1.5px solid #f0f0f0" }}>
                <div style={{ fontSize: "1.4rem", marginBottom: 8 }}>🏫</div>
                <div style={{ fontWeight: 700, color: "#111", marginBottom: 4 }}>Office</div>
                <div style={{ fontSize: "0.85rem", color: "#888" }}>CPE Department, Room 317<br />Mon – Fri, 8AM – 5PM</div>
              </div>
              <div style={{ flex: "1 1 220px", padding: "18px 20px", borderRadius: 12, border: "1.5px solid #f0f0f0" }}>
                <div style={{ fontSize: "1.4rem", marginBottom: 8 }}>💬</div>
                <div style={{ fontWeight: 700, color: "#111", marginBottom: 4 }}>Talk to your Adviser</div>
                <div style={{ fontSize: "0.85rem", color: "#888" }}>Your academic adviser is your first point of contact for advising-related questions.</div>
              </div>
            </div>
          </section>
    </StudentLayout>
  );
};

export default Help;
